### ISSUE TITLE
Archive:  oracle-xe-11.2.0-1.0.x86_64.rpm.zip End-of-central-directory signature not found.

### ISSUE THREAD

**Issue by yahonda** [cbandy/travis-oracle#10]
Thanks for providing travis-oracle.  Not every time but I'm seeing `Archive:  oracle-xe-11.2.0-1.0.x86_64.rpm.zip End-of-central-directory signature not found.` errors.
- Error message

```
Archive:  oracle-xe-11.2.0-1.0.x86_64.rpm.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of oracle-xe-11.2.0-1.0.x86_64.rpm.zip or
        oracle-xe-11.2.0-1.0.x86_64.rpm.zip.zip, and cannot find oracle-xe-11.2.0-1.0.x86_64.rpm.zip.ZIP, period.
The command ".travis/oracle/install.sh" failed and exited with 9 during .
Your build has been stopped.
```
- Full output
  https://travis-ci.org/rsim/oracle-enhanced/jobs/119416269

It does not reproduce every time. Also when the same commit pushed to my origin repository, it works fine.
- Push the same commit to my origin repository
  https://travis-ci.org/yahonda/oracle-enhanced/jobs/119414739

I'd like to address this since there is no work around found yet.

**Comment by cbandy** [comment]
> Full output https://travis-ci.org/rsim/oracle-enhanced/jobs/119416269

This build does not appear to be setting any login credentials. Your successful build does so on [lines 144–146](https://travis-ci.org/yahonda/oracle-enhanced/jobs/119414739#L144-L146).

It is normal that encrypted and hidden variables [do not appear in pull requests](https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings):

> we do not provide these values to untrusted builds, triggered by pull requests from another repository.

That being said, it is unfortunate that we don't emit a helpful error message in this case. I'll look into improving the error detection here.

**Comment by yahonda** [comment]
Thanks for the information.

Looks like it is hitting this.
https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

> Similarly, we do not provide these values to untrusted builds, triggered by pull requests from another repository.

 I'm getting `End-of-central-directory signature not found` errors for pull requests.  Once the pull request merged to upstream master branch. Travis CI works fine.

### What I have done:
- Reconfigure `Environment Variables`
  `ORACLE_LOGIN_password` and `ORACLE_LOGIN_ssousername` already created. 
  To make sure, I had deleted them and recreated these two environment variables.
- Still getting `Archive: oracle-xe-11.2.0-1.0.x86_64.rpm.zip End-of-central-directory signature not found` when tests running for pull requests
- Once this pull request merged to upstream master branch, Travis CI provided these two environment variables and unit test works successfully.  https://travis-ci.org/rsim/oracle-enhanced/jobs/119507078

I'm going to disable `Build pull requests` in setting and consider to implement [Encrypted Variables](https://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables)

Thanks for the advice.
