### ISSUE TITLE
Error: Cannot find module '/home/travis/download.js'

### ISSUE THREAD

**Issue by jgebal** [cbandy/travis-oracle#20]
Can you help me with my Travis setup?
The download fails for some reasons.
https://travis-ci.org/utPLSQL/utPLSQL-demo-project/builds/222538724#L238

```
Error: Cannot find module '/home/travis/download.js'

    at Function.Module._resolveFilename (module.js:338:15)

    at Function.Module._load (module.js:280:25)

    at Function.Module.runMain (module.js:497:10)

    at startup (node.js:119:16)

    at node.js:929:3
```

**Comment by cbandy** [comment]
`download.sh` and `download.js` are in the `.travis/oracle` directory.

`. .travis/oracle/download.sh` is sourcing the file [rather than executing it](https://superuser.com/questions/176783/). Remove the leading `. ` from the `download.sh` and `install.sh` lines and it should work:

```yaml
install:
  - .travis/oracle/download.sh
  - .travis/oracle/install.sh
```

**Comment by jgebal** [comment]
Worked, thank you.
