### ISSUE TITLE
[TypeError: Cannot read property 'data' of null]

### ISSUE THREAD

**Issue by jgebal** [cbandy/travis-oracle#21]
When I'm running my Travis builds, most of them fail with the above error message.
The build is passing however when I go to Oracle site and re-approve the license agreement.
https://travis-ci.org/utPLSQL/utPLSQL-demo-project/builds/222647318

I've accepted the Oracle License and have managed to get the file download locally using IE, Chrome and Firefox.

Did Oracle change something on their end that made the download solution unstable?

**Comment by cbandy** [comment]
I've not seen that before, or I don't remember what can cause it. 

> Did Oracle change something on their end that made the download solution unstable?

Quite probably. The error likely comes from trying to find/use the login form on Oracle's site. I can take a look tomorrow.

**Comment by jgebal** [comment]
I have a feeling it's something related to the cookies.

**Comment by jgebal** [comment]
I've switched to `language: phyton` for the project and it suddenly started working.
So another clue maybe it's related to the setting of:
```
language: java
jdk:
  - oraclejdk8
```

edit:
- this worked only for one build.
Second build on `phyton` is failing the same way as java did.

**Comment by jgebal** [comment]
What I have noticed is that on Oracle side I keep on getting asked to approve the licence, when I use link:
`https://edelivery.oracle.com/akam/otn/linux/oracle11g/xe/oracle-xe-11.2.0-1.0.x86_64.rpm.zip`
Does it mean that the cookie is no linger persisted?

**Comment by jgebal** [comment]
I think that Oracle has changed it's cookie policy so that they expire at the end of the session and session timeout is quite short now.

**Comment by jgebal** [comment]
When navigating to the link direcrly from browser I often get the message:
```
Sorry! 
 
In order to download products from Oracle Technology Network you must agree to the OTN license terms. 
 
Be sure that... 
 Your browser has "cookies" and JavaScript enabled. 
 You clicked on "Accept License" for the product you wish to download. 
 You attempt the download within 30 minutes of accepting the license. 
 ```

**Comment by jgebal** [comment]
@viniciusam was working on an accept-license-each-time solution.
Maybe that could solve the issue.
https://github.com/viniciusam/oracle-toolbox/blob/master/download.js

```casper.start(agreementUrl, function () {
   this.echo('Accepting License');
   this.evaluate(function () {
      acceptAgreement(window.self);
   });
});

// Try to access the download page, wait for redirection and submit the login form.
casper.thenOpen(downloadUrl).waitForUrl(/signon\.jsp$/, function (re) {
   this.echo('Injecting Login Info');
   this.evaluate(function (username, password) {
      document.getElementById('sso_username').value = username;
      document.getElementById('ssopassword').value = password;
      doLogin(document.LoginForm);
      // TODO: Check if login was successfull.
   }, paramUsername, paramPassword);
});
```

**Comment by cbandy** [comment]
I am able to reproduce this locally. From what I can tell, the problem is that we try to use jQuery to inspect the login form before jQuery is loaded. This is a simple patch that resolves the issue for me, can you give it a try?

```diff
diff --git a/download.js b/download.js
index d51aa5a..761003c 100644
--- a/download.js
+++ b/download.js
@@ -35,7 +35,7 @@ Phantom.createAsync({ parameters: { 'ssl-protocol': 'tlsv1' } }).then(function (
     .then(function () {
       return page.openPromise("https://edelivery.oracle.com/akam/otn/linux/" + env['ORACLE_FILE']).then(function (status) {
         if (status != 'success') throw "Unable to connect to oracle.com";
-        return page.waitForSelectorPromise('input[type=password]', 5000);
+        return page.waitForSelectorPromise('input[type=password]', 5000).delay(1000);
       })
       .catch(PhantomError, function (err) {
         return page.getPromise('plainText').then(function (text) {
```

I have a proper fix (wait until jQuery is loaded) working but need to clean it up before committing.

**Comment by jgebal** [comment]
Let me try that in the evening.

**Comment by jgebal** [comment]
Worked like a charm,
https://travis-ci.org/utPLSQL/utPLSQL-demo-project/builds/223333720

Let me know if you plan to have a release for this fix. I'd rather download your release from your repo (as per readme) than keep a copy of your project embedded.

Thanks for a quick turnaround on this.

**Comment by ChristopherDavenport** [comment]
I agree, keeping this project entirely in my `.travis.yml` if possible and currently builds are _inconsistent_. So a new release would help get CI operational again. 

Thanks for being so responsive.
