### ISSUE TITLE
Unable to use all ORACLE_LOGIN environment variables

### ISSUE THREAD

**Issue by mloskot** [cbandy/travis-oracle#23]
First, thanks for the downloader. It's been awesome, great time sver.

In SOCI project, we used it with great success (eg. https://travis-ci.org/SOCI/soci/jobs/281665636).
Lately, our builds stopped working due to incomplete downloads (eg. https://travis-ci.org/SOCI/soci/jobs/291261632) and I'm unclear what is the reason. If I sign in to the Oracle website via web browser using the downloader's credentials, all works.

I noticed a difference in the downloader output - now it prints:
```
Unable to use all ORACLE_LOGIN environment variables: ["password","ssousername"]
```

What does this message mean?

Does it mean anything changed in Travis CI and I have to re-add the environment variables with credentials to re-hash them?

Has Oracle changed their login form?

Unfortunately, my JS fu is running very short to figure out  from the download.js :(
I'd appreciate any insights.

**Comment by cbandy** [comment]
That probably means the login form changed. Can you check two things for me please?

Visit the login page in your browser and with the developer console:

1. Does [`jQuery(document.forms[0])`](https://github.com/cbandy/travis-oracle/blob/b054035bf5e3267cf4849078f80556f69823f6b1/download.js#L78) evaluate to the login form? If not, you'll need to change the array index until we can identify the form some other way.

2. What are the `name` attributes of the fields of the login form? If they are no longer `ssousername` and `password`, you'll need to set new environment variables that match the names.

**Comment by cbandy** [comment]
It looks like the form fields have changed names. Try using `ORACLE_LOGIN_userid` and `ORACLE_LOGIN_pass` instead.

**Comment by mloskot** [comment]
@cbandy Yes, indeed. I was about to update you about that, but didn't have chance to try the changed envrionment variables yet

**Comment by mloskot** [comment]
> Try using `ORACLE_LOGIN_userid` and `ORACLE_LOGIN_pass` instead.

I've just tried https://travis-ci.org/SOCI/soci/jobs/291704587
and the "Unable to use all ORACLE_LOGIN environment variables" is gone now.

Something is not working with authentication though and ~20KB non-ZIP file is downloaded.

It seems to me that Oracle has added new hidden fields to the form, especially `fk` field getting generated value:

* 1st load

```
<input type="hidden" id="clientOffset" name="clientOffset" />
<input type="hidden" id="fk" name="fk" value="6192307_9d12540afc45dfe2839073f8f02e21fc1ca6ac69b1a665d96e6166741b91110e"/>
```

* 2nd load

```
<input type="hidden" id="clientOffset" name="clientOffset" />
<input type="hidden" id="fk" name="fk" value="6189592_a7646401171dcbf710b87585d8ab9fd3a3e6c425b0d57baa23662c07ddc51198"/>
```

etc

**Comment by tschf** [comment]
I think Oracle change something in the last fortnight. I did some analysis on another of my projects about a week back and came up with the following:

1. Request file (edelivery)
2. Redirect to login.do
3. User submits, which sends a post to loginAuth.do. Response contains \<meta http-equiv="refresh" content="3;URL=/oaam_server/authJump.do?jump=false"/\> which causes 4.
4. Call GET request to authJump.do (as that's what happens in the meta refresh above)
5. Redirected to updateLoginStatus (via HTTP 302). The contains a form that is auto submitted in the browser, so you have to just resubmit the page to cred_submit (as from the form)
6. Do a POST to cred_submit (as is expected from 5)

![](https://user-images.githubusercontent.com/1747643/31592778-57553c28-b276-11e7-84d9-176b81000a1a.png)

Also, the login form now has the following input fields (loginAuth.do):

//1. fk - a unique token that is returned in the form
//2. clientOffset - The offset hours from GMT. 
//3. userid
//4. pass 

I'm not sure how the request flow differs from what it was before, if any steps can be skipped. 
Anyway, hope it helps.

**Comment by cbandy** [comment]
Thanks, @mloskot, @tschf. [All the form fields](https://github.com/cbandy/travis-oracle/blob/b054035bf5e3267cf4849078f80556f69823f6b1/download.js#L81) are captured and sent when submitting the login form. The trouble is the multiple new HTML pages returned by OAAM Server.

As it is now, `download.js` handles a few initial redirects, then uses the JavaScript context of the headless browser to parse the HTML form and write any cookies to a file. _cURL_ submits the login form POST, handles the remaining redirects, and writes the ZIP file to disk.

To handle these new HTML pages _after_ the login form, I think we'll have to stay in PhantomJS longer. Last I checked, however, PhantomJS wasn't very good when it came to the final file (i.e. getting a 200 MiB file out of the browser context.)

🤔 Perhaps the solution here is to first login _without_ having requested the large file. Though, I'd like to not hardcode any new URLs... I'll try to devise a hotfix/workaround tomorrow. Any suggestions?

**Comment by mloskot** [comment]
@cbandy I wish I could help, but I know close to nothing about Node/PhantomJS, I'm afraid

**Comment by cbandy** [comment]
I have [something working](https://travis-ci.org/cbandy/travis-oracle/builds/294012261) in Precise jobs, but more needs to be done to get all the right cookies out of the newer PhantomJS in Trusty jobs.

**Comment by cbandy** [comment]
> get all the right cookies out of the newer PhantomJS

It turns out that wasn't so hard. I will occasionally encounter [login failures](https://travis-ci.org/cbandy/travis-oracle/builds/294038520), however, that I haven't been able to diagnose.

**Comment by cbandy** [comment]
Please try out the hotfix branch, and if it resolves this issue for you I'll cut a new release in the coming days. 💛

**Comment by mloskot** [comment]
@cbandy I've switched our build to the hotfix (https://github.com/SOCI/soci/commit/3992cd8f6b8316d57e8c86e44ecbfa8e350055b6) and the build based on Oracle passed: https://travis-ci.org/SOCI/soci/jobs/294782925

Awesome, thanks!

**Comment by gabmontes** [comment]
@cbandy I had the same issue and can also confirm your `hotfix` branch solved the problem.

Thanks!!
