### ISSUE TITLE
Work with Travis containers

### ISSUE THREAD

**Issue by cbandy** [cbandy/travis-oracle#3]
The [container-based infrastructure](http://docs.travis-ci.com/user/workers/container-based-infrastructure/) disallows `sudo`. Either
1. Find a way to install without `sudo`, or
2. Document the required `.travis.yml` settings.

**Comment by jayvdb** [comment]
I've had a crack at option 1, with https://github.com/cbandy/travis-oracle/pull/9

Currently only failing at ruby installation, which I've logged a support request for: https://github.com/kubo/ruby-oci8/issues/124
