### ISSUE TITLE
Fail Oracle Website

### ISSUE THREAD

**Issue by williamgueiros** [cbandy/travis-oracle#6]
if oracle website have problems, the script don't show the problem, and process continue.

![captura-de-tela-2015-10-15-_s-18 20 47](https://cloud.githubusercontent.com/assets/19972/10533979/db8f440e-73a6-11e5-9914-10a7dbbddbc6.png)
![captura-de-tela-2015-10-15-_s-18 20 11](https://cloud.githubusercontent.com/assets/19972/10533983/ddb504d0-73a6-11e5-95bc-bea8776325ba.png)
![screen shot 2015-10-16 at 1 36 01 am](https://cloud.githubusercontent.com/assets/19972/10533984/e28a21ac-73a6-11e5-91e8-9ce107fb81de.png)

**Comment by cbandy** [comment]
Which process continues? Does Travis execute anything after the message on line 140?

**Comment by williamgueiros** [comment]
if you have problem in phantomjs the curl run and after that you have a file rpm.zip 1 kb
and doesn't show the real problem is in oracle website or delay on website .

link: https://github.com/cbandy/travis-oracle/blob/master/download.sh#L11
travis ci : https://travis-ci.org/williamgueiros/sequelize/builds/85612619

after line 140 the travis-ci stopped.

**Comment by williamgueiros** [comment]
@cbandy ping

**Comment by cbandy** [comment]
Has the site been unresponsive frequently?

This is the nature of pipes, unfortunately: Both `phantomjs` and `curl` run at the same time. We want to continue using pipe, I think so that no other process can see the secure variables (username and password) as they are passed to `curl`.

We can try to increase the verbosity in `download.js`, or execute `curl` from within.

**Comment by cbandy** [comment]
> or execute `curl` from within.

Piping to a child process is [not supported by PhantomJS](https://github.com/ariya/phantomjs/issues/11446).

**Comment by williamgueiros** [comment]
good catch

**Comment by williamgueiros** [comment]
\o/
