### ISSUE TITLE
download.js errorCode: 299 Bad Request

### ISSUE THREAD

**Issue by jayvdb** [cbandy/travis-oracle#8]
My download.js is not modified, and while running many builds I encountered this error on one of them.

```
+exec node download.js
{ errorCode: 299,
  errorString: 'Error downloading https://login.oracle.com/pls/orasso/orasso.wwsso_app_admin.ls_login?Site2pstoreToken=v1.2~CA55CD32~... - server replied: Bad Request',
  id: 2,
  url: 'https://login.oracle.com/pls/orasso/orasso.wwsso_app_admin.ls_login?Site2pstoreToken=v1.2~CA55CD32~A...' }
Unable to connect to oracle.com
```

https://travis-ci.org/jayvdb/travis-oracle/jobs/119102903

**Comment by cbandy** [comment]
`errorCode: 299` is [QNetworkReply::UnknownContentError](http://phantomjs.org/api/webpage/handler/on-resource-error.html). I'm not sure what that exactly means or what could have caused it. I'm going to assume its a temporary network issue...

It looks like we've reported everything we can out of PhantomJS and triggered a build error. I'm going to close this as "not-a-bug". Please reopen if you disagree.

**Comment by jayvdb** [comment]
No worries.  Just thought I would mention it, especially in case we see it again in the future.
